services:

    ekreative_redmine_login.user_factory:
        class: AppBundle\Redmine\RedmineUserFactory
        arguments:
            - @doctrine

    site_author.listener:
        class: AppBundle\AuthorEditor\AuthorEditorListener
        arguments:
            - @security.token_storage
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }

    project_type:
        class: AppBundle\Form\ProjectType
        arguments:
            - @router
            - @project_transformer
        tags:
            - { name: form.type, alias: project }

    project_transformer:
            class: AppBundle\Form\ModelTransformer\ProjectModelTransformer
            arguments:
                - @doctrine.orm.entity_manager
                - @projects

    projects:
        class: AppBundle\Redmine\Projects
        arguments:
            - @ekreative_redmine_login.client_provider
            - @security.token_storage
#            - @projects_cache

    projects_cache:
        class: Doctrine\Common\Cache\RedisCache
        calls:
            - [setRedis, [@redis]]
            - [ setNamespace, [ 'sm:p:' ]]

    redis:
        class: Redis
        calls:
            - [connect, [%redis%, 6379]]
